/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FrontalButton {
        "class": string;
        "color": string;
        "disabled": boolean;
        "text": string;
    }
    interface FrontalInput {
        "color": string;
        "disabled": boolean;
        "label": string;
        "name": string;
        "validator": Array<string>;
        "value": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFrontalButtonElement extends Components.FrontalButton, HTMLStencilElement {
    }
    var HTMLFrontalButtonElement: {
        prototype: HTMLFrontalButtonElement;
        new (): HTMLFrontalButtonElement;
    };
    interface HTMLFrontalInputElement extends Components.FrontalInput, HTMLStencilElement {
    }
    var HTMLFrontalInputElement: {
        prototype: HTMLFrontalInputElement;
        new (): HTMLFrontalInputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "frontal-button": HTMLFrontalButtonElement;
        "frontal-input": HTMLFrontalInputElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FrontalButton {
        "class"?: string;
        "color"?: string;
        "disabled"?: boolean;
        "text"?: string;
    }
    interface FrontalInput {
        "color"?: string;
        "disabled"?: boolean;
        "label"?: string;
        "name"?: string;
        "validator"?: Array<string>;
        "value"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "frontal-button": FrontalButton;
        "frontal-input": FrontalInput;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "frontal-button": LocalJSX.FrontalButton & JSXBase.HTMLAttributes<HTMLFrontalButtonElement>;
            "frontal-input": LocalJSX.FrontalInput & JSXBase.HTMLAttributes<HTMLFrontalInputElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
